### PR TITLE
Enable workflows on fork-based PRs part II

### PR DESCRIPTION
**Pull request by grafjo**

### CODE REVIEW

**Review by sbckr — APPROVED** [review]
LGTM

**Comment by sbckr** [comment]
@grafjo please rebase as this branch is out-of-date

**Comment by grafjo** [comment]
> @grafjo please rebase as this branch is out-of-date

ok rebase is done

**Comment by sbckr** [comment]
@grafjo I apologize for the inconvenience caused, but could you please rebase again

**Comment by grafjo** [comment]
> @grafjo I apologize for the inconvenience caused, but could you please rebase again

no worries - rebase is done @sbckr

**Comment by grafjo** [comment]
is already in master-branch

**Pull request closed without merging**
